CREATE DATABASE Vitoria_lanches;
USE Vitoria_lanches;

CREATE TABLE TB_USUARIO (
ID_TB_USUARIO INTEGER PRIMARY KEY AUTO_INCREMENT,
EMAIL_TB_USUARIO VARCHAR(40) UNIQUE NOT NULL,
SENHA_TB_USUARIO VARCHAR(100) NOT NULL,
TIPO_TB_USUARIO VARCHAR(50) NOT NULL,
CPF_CNPJ_TB_USUARIO VARCHAR(14)
);

CREATE TABLE TB_CLIENTE (
TB_CLIENTE_ID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
TB_CLIENTE_NOME VARCHAR(128) NOT NULL,
TB_CLIENTE_SOBRENOME VARCHAR(128) NOT NULL,
TB_CLIENTE_TEL VARCHAR(32) NOT NULL,
TB_CLIENTE_ENDERECO VARCHAR(128),
TB_CLIENTE_ENDERECO_NUM VARCHAR(8),
TB_CLIENTE_BAIRRO VARCHAR(128),
TB_CLIENT_CIDADE VARCHAR(128),
TB_CLIENTE_UF CHAR(2)
);

-- creating a new foreign key and putting into our references:

ALTER TABLE TB_CLIENTE
ADD COLUMN FK_USER_ID INTEGER NOT NULL;

ALTER TABLE TB_CLIENTE
ADD CONSTRAINT PK_TB_USUARIO_FK_TB_CLIENTE
FOREIGN KEY(FK_USER_ID)
REFERENCES TB_USUARIO (ID_TB_USUARIO);

CREATE TABLE TB_TIPO_PRODUTO (
TB_TIPO_PRODUTO_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
TB_TIPO_PRODUTO_DESC VARCHAR(250) NOT NULL
);

CREATE TABLE TB_PRODUTO(
TB_PRODUTO_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
TB_PRODUTO_NOME VARCHAR(128) NOT NULL,
TB_TIPO_PRODUTO_ID INTEGER,
TB_PRODUTO_DESC VARCHAR(512),
TB_PRECO_PRODUTO_UNIT DECIMAL(10,2)
);

ALTER TABLE TB_PRODUTO 
ADD CONSTRAINT PK_TB_PRODUTO_ID_FK_TB_PRODUTO
FOREIGN KEY (TB_TIPO_PRODUTO_ID)
REFERENCES TB_TIPO_PRODUTO(TB_TIPO_PRODUTO_ID);

CREATE TABLE TB_PEDIDO_VENDA(
TB_PEDIDO_VENDA_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
TB_CLIENTE_ID INTEGER NOT NULL,
TB_PEDIDO_VENDA_DATA DATETIME NOT NULL,
TB_PEDIDO_VENDA_VAL_TOTAL DECIMAL(10,2) NOT NULL,
TB_PEDIDO_VENDA_STATUS VARCHAR(16) NOT NULL,
TB_PEDIDO_VENDA_FORMA_PAG VARCHAR(32) NOT NULL,
TB_PEDIDO_VENDA_OBS VARCHAR(500)
);

ALTER TABLE TB_PEDIDO_VENDA
ADD CONSTRAINT PK_TB_CLIENTE_ID_FK_TB_PEDIDO_VENDA
FOREIGN KEY (TB_CLIENTE_ID)
REFERENCES TB_CLIENTE(TB_CLIENTE_ID);

CREATE TABLE TB_PEDIDO (
TB_PEDIDO_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
TB_PRODUTO_ID INTEGER,
TB_PEDIDO_VENDA_ID INTEGER,
TB_PEDIDO_PRODUTO_QTD INTEGER NOT NULL,
TB_PEDIDO_PRODUTO_PRECO_UNIT DECIMAL(10,2) NOT NULL,
TB_PEDIDO_PRODUTO_PRECO_TOTAL DECIMAL(10,2) NOT NULL
);

ALTER TABLE TB_PEDIDO 
ADD CONSTRAINT PK_TB_PRODUTO_ID_FK_TB_PEDIDO
FOREIGN KEY (TB_PRODUTO_ID)
REFERENCES TB_PRODUTO(TB_PRODUTO_ID);

ALTER TABLE TB_PEDIDO
ADD CONSTRAINT PK_TB_PEDIDO_VENDA_ID_FK_TB_PEDIDO
FOREIGN KEY (TB_PEDIDO_VENDA_ID)
REFERENCES TB_PEDIDO_VENDA (TB_PEDIDO_VENDA_ID);

-- SOLI DEO GLORIA!